---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install nvm"
  become: yes
  npm:
    name: n
    global: yes
    production: yes
- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0
  
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy artifact to web dir
  copy:
    src: files/artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: unzip files
  shell: |
     tar -xzvf artifact.tar.gz

- name: "installing node"
  shell: |
      cd ~/backend
      npm i

- name: Executing node
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js npm -- start

- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu